package main

import (
	"fmt"
	. "github.com/deckarep/golang-set/v2"
	"strings"
)

type Match struct {
	A          string
	B          string
	Offset     int
	Mismatches int
}

func BestMatch(a, b string, maxOffset int) (offset int, mismatches int, ok bool) {

	bestMismatches := len(a) + len(b)
	bestOffset := 0

	for shift := -maxOffset; shift <= maxOffset; shift++ {

		mm := 0
		overlap := 0

		for i := 0; i < len(a); i++ {

			j := i + shift

			if j < 0 || j >= len(b) {
				continue
			}

			overlap++

			if a[i] != b[j] {
				mm++
			}
		}

		if overlap == 0 {
			continue
		}

		if mm < bestMismatches {
			bestMismatches = mm
			bestOffset = shift
		}
	}

	return bestOffset, bestMismatches, true
}

func FuzzyIntersect(
	a Set[string],
	b Set[string],
	maxOffset int,
	maxMismatches int,
) []Match {

	var matches []Match

	for x := range a.Iter() {
		for y := range b.Iter() {

			offset, mm, ok := BestMatch(x, y, maxOffset)

			if !ok {
				continue
			}

			if mm <= maxMismatches {
				matches = append(matches, Match{
					A:          x,
					B:          y,
					Offset:     offset,
					Mismatches: mm,
				})
			}
		}
	}

	return matches
}

func main() {

	m_250_2020 := `
		AAAGGCCTTATTCGTCAAGT
		AAAGTCGAAGGTTGTCAATT
		ACGGGCTTAGGTCCTCAATG
		AGAACCGAAGTTCGTTGAGT
		AGGGACCTAATTCCATATTT
		AGGGCCAAAGGTCCTCCGCT
		AGGGCCAAAGGTCCTCCGCT
		AGGGCCGAAAGTCCCATGCC
		AGGGCCGGAAGTCCCCAATG
		AGGGCCGGAAGTCCCCAATG
		AGGGCCGTAAGTCATCCACT
		AGGGCCGTTAGTCCTTATCG
		AGGGGCGAAAGTCCCTTATC
		AGGGTCAATGGTCCCCAAGT
		AGGGTCAATGGTCCCCAAGT
		AGTGACGAAAGACCCCAGTG
		CGGGACGTAAGTCCCTAACG
		GGAGGCGATGGTCCCTAACC
		GGGGACCGAAGTCCCCGGGC
		GGGGCCGAAGGTCCTCAAGA
		TGAGGCTTTAGTCCCCAATC
		TGAGGCTTTAGTCCCCAATC
	`

	m_250_650 := `
		AAAGGACCAAAGGCCTTATT
		AACGGGCTTAGGTCCTCAAT
		AAGGGGCGAAAGTCCCTTAT
		AAGTGACGAAAGACCCCAGT
		ACGGGTCAAACGACCCTAGT
		AGGAGGCGATGGTCCCTAAC
		ATGAGGCTTTAGTCCCCAAT
		ATGAGGCTTTAGTCCCCAAT
		CAGGGACCTAATTCCATATT
		CAGGGCCAAAGGTCCTCCGC
		CAGGGCCAAAGGTCCTCCGC
		CAGGGCCGAAAGTCCCATGC
		CAGGGCCGTAAGTCATCCAC
		GAGGGCCGTTAGTCCTTATC
		GCGGGACGTAAGTCCCTAAC
		TAGGGACAGAAGTCCCCGAA
		TAGGGACAGAAGTCCCCGAA
		TAGGGCCGGAAGTCCCCAAT
		TAGGGCCGGAAGTCCCCAAT
		TGGGGACCGAAGTCCCCGGG
		TGGGGCCGAAGGTCCTCAAG
	`

	m_25_2020 := `
		TCCGCCCCAGCGAAGGAGAC
		TACACCCATGCAGAGGGGAC
		TTCGCTCAAGCGACGAAGTC
		TCAGCCAACGACAGGAGGAC
		TCAGCGCCTTCCCCGGTGAT
		GCCTCCTAATCGATGGAAAC
		CACCCCGACTCGAGGAGGAT
		AGCGTCCCTTCCTTGGGGAC
		TATCCGCCAGCATCGGAGGT
	`

	m_100_2020 := `
		GCGTTAGGGACTTACGTCCC
		CGATTGGGGACTAAAGCCTC
		CGATTGGGGACTAAAGCCTC
		CAGGTGGGGACCAACGCCCC
		GGGTTAGGGACCATCGCCTC
		CACTTGGGGACCATTGACCC
		GCTCTGGGGACCGAAGTCCC
		CAGTGGATGACTTACGGCCC
		CCATTCGTGACCGACGTCCC
		GGGCTAGGGACAGAAGTCCC
		CCACTGGGGTCTTTCGTCAC
		CAGCGGAGGACCTTTGGCCC
		CCGGAAAGGACCAAAGGCCT
		CGCTGAGGGACTGTCGTCAG
		CCCGAGGGGACTTTTGGCCA
	`

	m_500_2020 := `
		GGGCTAGGGACAGAAGTCCC
		GGGCTAGGGACAGAAGTCCC
		CAGTTAGGGCCGGAAGTCCC
		CAGTTAGGGCCGGAAGTCCC
		CGGACAGGGCCGAAAGTCCC
		GCGTTAGGGACTTACGTCCC
		GCGTTAGGGACTTACGTCCC
		CGGGTAGGGCATAAAGTCTC
		CGATTGGGGACTAAAGCCTC
		CGATTGGGGACTAAAGCCTC
		GGCATAGGGACCAAAGTCAT
		GAGGCAGGGCCAAAGGTCCT
		GAGGCAGGGCCAAAGGTCCT
		CAGGTGGGGACCAACGCCCC
		GGATCAGGGCCGTAAGTCAT
		GGGCTAGTGACAAACGCCTC
		CGGGAAGGGGCGAAAGTCCC
		GGGTTAGGGACCATCGCCTC
		TGGGTGGGGCCGAAGGTCCT
		CAAATATGGAATTAGGTCCC
		CGCCGGTGGCCAAAAGTCCC
		CGCCGGTGGCCAAAAGTCCC
		GCTCTGGGGACCGAAGTCCC
		CGAATAAGGCCTTTGGTCCT
		GGGCGAAGGCCAAACGACCC
	`

	m_1000_2020 := `
		GCTAGGGACAGAAGTCCCCG
		GCTAGGGACAGAAGTCCCCG
		GTTAGGGCCGGAAGTCCCCA
		GTTAGGGCCGGAAGTCCCCA
		GTTAGGGACTTACGTCCCGC
		GTTAGGGACTTACGTCCCGC
		GTTAGGGACTTACGTCCCGC
		ATTGGGGACTAAAGCCTCAT
		ATTGGGGACTAAAGCCTCAT
		GGTAGGGCATAAAGTCTCTA
		GCTAGTGACAAACGCCTCCT
		TCTGGGGACCGAAGTCCCCG
		TCTGGGGACCGAAGTCCCCG
		GGTGGGGACCAACGCCCCTG
		GGTGGGGACCAACGCCCCTG
		GACAGGGCCGAAAGTCCCAT
		GTTAGGGACCATCGCCTCCT
		GGTGGGGCCGAAGGTCCTCA
		GGCAGGGCCAAAGGTCCTCC
		GGCAGGGCCAAAGGTCCTCC
		AATATGGAATTAGGTCCCTG
		CCGGTGGCCAAAAGTCCCCT
		CCGGTGGCCAAAAGTCCCCT
		ATCAGGGCCGTAAGTCATCC
		AATAAGGCCTTTGGTCCTTT
		GCGAAGGCCAAACGACCCTA
		AGTGGTGACCGACGCCACCG
	`

	r0 := NewSet(strings.Fields(m_250_2020)...)

	r1 := NewSet(strings.Fields(m_250_650)...)
	r2 := NewSet(strings.Fields(m_25_2020)...)
	r3 := NewSet(strings.Fields(m_100_2020)...)
	r4 := NewSet(strings.Fields(m_500_2020)...)
	r5 := NewSet(strings.Fields(m_1000_2020)...)

	rx := []Set[string]{r1, r2, r3, r4, r5}

	fmt.Println(rx)

	for i, r := range rx {
		fmt.Println(i, r0.Intersect(r))
	}

	for i, r := range rx {
		matches := FuzzyIntersect(r0, r, 2, 2)
		fmt.Println(i, matches)
	}
}
